#include "ast.h"
#include "closure_conversion.h"
#include "eval.h"
#include "global.h"
#include "ll.h"
#include "parse.h"
#include "scope.h"
#include "tokenise.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv) {
  int err;
  printf("Starting...\n");
  if (argc < 2) {
    printf("First argument must be code file\n");
    return ARG_ERROR;
  }
  if (argc < 3) {
    printf("Second argument must be assembly output file\n");
    return ARG_ERROR;
  }
  char *outfile = argv[2];
  LL *h = make_list();
  printf("Loading file: %s\n", argv[1]);
  FILE *fp = fopen(argv[1], "r");
  int tokenise_result = tokenise(fp, h);
  fclose(fp);
  if (tokenise_result != 0) {
    printf("Compiling failed.\n");
    return tokenise_result;
  }
  printf("Parsing (building AST)...\n");
  AST *global = make_globalExp();
  int parse_result = parse(h, global);
  free_tokens(h);
  if (parse_result != 0) {
    printf("Compiling failed.\n");
    return parse_result;
  }
  printf("Processing global defines...\n");
  int process_defines_result = process_defines(global);
  if (process_defines_result != 0) {
    printf("Compiling failed.\n");
    return process_defines_result;
  }
  printf("Parsing (processing special forms)...\n");
  int parse_special_forms_result = parse_special_forms(global);
  if (parse_special_forms_result != 0) {
    printf("Compiling failed.\n");
    return parse_special_forms_result;
  }
  printf("Scoping...\n");
  make_scopes(global);
  printf("Closure converting...\n");
  int closure_convert_result = closure_convert(global);
  if (closure_convert_result != 0) {
    printf("Compiling failed.\n");
    return closure_convert_result;
  }
  printf("Opening output file...\n");
  FILE *output = fopen(outfile, "w+");
  if (output == NULL) {
    printf("ERROR! Could not open output file %s\n", outfile);
    perror("Failed: ");
    return IO_ERROR;
  }
  fprintf(output, "; Assembly code generated by compiler\n");
  printf("Emitting assembly code...\n");
  eval(output, global, 0, 0);
  fclose(output);
  printf("\nDone emitting. Now further compile and link with:\n");
  printf("nasm -f elf64 %s -o obj.o\n", outfile);
  printf(
      "gcc -no-pie -o executable obj.o lib/libclosure.a lib/libstandard.a\n");
  free_ast(global);
  return 0;
}
